/**
 * Extract Tailwind CSS classes from denote's server components.
 *
 * Scans class= attributes in .tsx files and writes a deduplicated,
 * sorted constant to lib/server_classes.ts for use by the CLI.
 *
 * Usage: deno task extract-classes
 */

/** Find the matching closing brace, aware of string/template literal boundaries. */
function findClosingBrace(source: string, start: number): number {
  let depth = 1;
  let i = start;
  while (i < source.length && depth > 0) {
    const ch = source[i];
    if (ch === "\\") {
      i += 2;
      continue;
    }
    if (ch === '"') {
      i++;
      while (i < source.length && source[i] !== '"') {
        if (source[i] === "\\") i++;
        i++;
      }
      i++;
      continue;
    }
    if (ch === "'") {
      i++;
      while (i < source.length && source[i] !== "'") {
        if (source[i] === "\\") i++;
        i++;
      }
      i++;
      continue;
    }
    if (ch === "`") {
      i++;
      while (i < source.length && source[i] !== "`") {
        if (source[i] === "\\") i++;
        i++;
      }
      i++;
      continue;
    }
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return i;
    }
    i++;
  }
  return -1;
}

function addTokens(set: Set<string>, content: string) {
  for (const token of content.split(/\s+/)) {
    if (token) set.add(token);
  }
}

/**
 * Extract Tailwind class tokens from a source string.
 * Handles:
 *   - class="static classes"
 *   - class={`template ${cond ? "a" : "b"} literal`}
 *   - class={expr ? "classes" : "other"}
 */
export function extractClasses(source: string): Set<string> {
  const classes = new Set<string>();
  const classRe = /class(?:Name)?=/g;

  let match;
  while ((match = classRe.exec(source)) !== null) {
    const afterEquals = match.index + match[0].length;
    const ch = source[afterEquals];

    if (ch === '"') {
      // Static: class="..."
      const closeQuote = source.indexOf('"', afterEquals + 1);
      if (closeQuote === -1) continue;
      addTokens(classes, source.slice(afterEquals + 1, closeQuote));
    } else if (ch === "{") {
      // JSX expression: class={...}
      const closeBrace = findClosingBrace(source, afterEquals + 1);
      if (closeBrace === -1) continue;
      const expr = source.slice(afterEquals + 1, closeBrace);

      // Extract all double-quoted strings within the expression
      const strRe = /"([^"]*)"/g;
      let strMatch;
      while ((strMatch = strRe.exec(expr)) !== null) {
        addTokens(classes, strMatch[1]);
      }

      // Extract template literal raw text (between backticks, removing ${...})
      const tmplRe = /`([^`]*)`/g;
      let tmplMatch;
      while ((tmplMatch = tmplRe.exec(expr)) !== null) {
        const raw = tmplMatch[1].replace(/\$\{[^}]*\}/g, " ");
        addTokens(classes, raw);
      }
    }
  }

  return classes;
}

// ── CLI entry point ──────────────────────────────────────────────

async function* walkTsx(dir: string): AsyncGenerator<string> {
  for await (const entry of Deno.readDir(dir)) {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory) {
      yield* walkTsx(path);
    } else if (entry.name.endsWith(".tsx")) {
      yield path;
    }
  }
}

if (import.meta.main) {
  const PKG_DIR = new URL("../", import.meta.url).pathname;

  // Server-rendered files (NOT islands — Vite handles those)
  const dirs = [
    `${PKG_DIR}components`,
    `${PKG_DIR}routes`,
  ];

  const allClasses = new Set<string>();

  for (const dir of dirs) {
    for await (const filePath of walkTsx(dir)) {
      const source = await Deno.readTextFile(filePath);
      for (const cls of extractClasses(source)) {
        allClasses.add(cls);
      }
    }
  }

  const sorted = [...allClasses].sort();
  const output =
    `// AUTO-GENERATED by scripts/extract-classes.ts — do not edit manually
// Run: deno task extract-classes
export const SERVER_CLASSES =
  ${JSON.stringify(sorted.join(" "))};
`;

  const outPath = `${PKG_DIR}lib/server_classes.ts`;
  await Deno.writeTextFile(outPath, output);
  console.log(`Wrote ${sorted.length} classes to lib/server_classes.ts`);
}
