#!/usr/bin/env -S deno run -A
/**
 * Denote CLI — AI-native documentation framework
 *
 * @module
 *
 * Command-line interface for developing, building, and validating Denote
 * documentation sites. Not intended for programmatic import — use
 * `@denote/core` (the main entry point) instead.
 *
 * @example Run the dev server
 * ```sh
 * deno run -A jsr:@denote/core/cli dev
 * ```
 *
 * @example Build for production
 * ```sh
 * deno run -A jsr:@denote/core/cli build
 * ```
 */

import denoConfig from "./deno.json" with { type: "json" };
import { SERVER_CLASSES } from "./lib/server_classes.ts";
const VERSION = denoConfig.version;

// ANSI colors
const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
const green = (s: string) => `\x1b[32m${s}\x1b[0m`;
const cyan = (s: string) => `\x1b[36m${s}\x1b[0m`;
const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;
const red = (s: string) => `\x1b[31m${s}\x1b[0m`;

function printHelp() {
  console.log(`
${bold("🦕 Denote")} v${VERSION} — AI-native documentation framework

${bold("USAGE")}
  denote <command> [options]

${bold("COMMANDS")}
  dev              Start development server
  build            Build static site for production
  validate         Check content, config, and navigation for issues
  mcp [--http]     Start MCP server for AI agents

${bold("OPTIONS")}
  -h, --help       Show this help message
  -v, --version    Show version number
  -p, --port       Port for dev server (default: 8000)

${bold("EXAMPLES")}
  denote dev                    ${dim("# Start dev server")}
  denote build                  ${dim("# Build for production")}
  denote mcp --http --port 3100 ${dim("# Start MCP server")}
`);
}

async function loadUserConfig(): Promise<
  { config: unknown; configPath: string }
> {
  const candidates = [
    "denote.config.ts",
    "denote.config.js",
  ];

  for (const name of candidates) {
    const absPath = `${Deno.cwd()}/${name}`;
    try {
      await Deno.stat(absPath);
      const fileUrl = new URL(absPath, "file:///");
      const mod = await import(fileUrl.href);
      return { config: mod.config || mod.default, configPath: absPath };
    } catch (e) {
      // Log non-NotFound errors to help debug config loading issues
      if (!(e instanceof Deno.errors.NotFound)) {
        console.error(`  [denote] Error loading ${name}:`, e);
      }
    }
  }

  console.error(red("Error: No config file found."));
  console.error(`Expected one of: ${candidates.join(", ")}`);
  console.error(
    `Run ${cyan("deno run -Ar jsr:@denote/init")} to create a new project.`,
  );
  Deno.exit(1);
}

/**
 * Generate build files in the .denote/ hidden directory.
 * These are gitignored and regenerated by the CLI on every dev/build.
 *
 * Generated files use "@denote/core" package specifiers, which resolve
 * via the user's import map (local workspace or JSR). Server component
 * Tailwind classes are safelisted via @source inline() so no filesystem
 * path scanning is needed.
 */
async function generateBuildFiles(configPath: string, port = 8000) {
  const cwd = Deno.cwd();
  const dotDir = `${cwd}/.denote`;
  const header = "// @denote-generated — do not edit, regenerated by CLI\n";

  await Deno.mkdir(dotDir, { recursive: true });

  // Copy base CSS locally — @import can't resolve package specifiers,
  // but fetch() works with both file:// and https:// URLs
  const stylesUrl = new URL("assets/styles.css", import.meta.url);
  const resp = await fetch(stylesUrl);
  if (!resp.ok) {
    throw new Error(`Failed to load denote base styles: ${resp.statusText}`);
  }
  await Deno.writeTextFile(`${dotDir}/denote-base.css`, await resp.text());

  // ── main.ts — entry point that Vite/Fresh uses ──────────────
  await Deno.writeTextFile(
    `${dotDir}/main.ts`,
    `${header}import { denote } from "@denote/core";
import { config } from "${configPath}";
import { join } from "jsr:@std/path@1";

const contentDir = Deno.env.get("DENOTE_CONTENT_DIR") ||
  join(Deno.cwd(), "content", "docs");

export const app = denote({ config, contentDir });
`,
  );

  // ── client.ts — client-side entry (CSS imports) ─────────────
  await Deno.writeTextFile(
    `${dotDir}/client.ts`,
    `${header}import "./styles.css";
`,
  );

  // ── styles.css — Tailwind + Denote styles ───────────────────
  await Deno.writeTextFile(
    `${dotDir}/styles.css`,
    `/* @denote-generated — do not edit, regenerated by CLI */
@import "tailwindcss";

@source inline("${SERVER_CLASSES}");
@source "../";

@variant dark (&:where(.dark, .dark *));

@import "./denote-base.css";
`,
  );

  // ── vite.config.ts (includes config hot-reload plugin) ──────
  await Deno.writeTextFile(
    `${dotDir}/vite.config.ts`,
    `${header}import { defineConfig, type Plugin } from "vite";
import { fresh } from "@fresh/plugin-vite";
import tailwindcss from "@tailwindcss/vite";
import { setConfig, islandSpecifiers } from "@denote/core";

const DENOTE_CONFIG_PATH = "${configPath}";

/** Vite plugin: hot-reload denote.config.ts without restarting the dev server */
function denoteConfigHmr(): Plugin {
  return {
    name: "denote-config-hmr",
    configureServer(server) {
      server.watcher.on("change", async (file: string) => {
        if (file === DENOTE_CONFIG_PATH) {
          try {
            const mod = await import(new URL(DENOTE_CONFIG_PATH + "?t=" + Date.now(), "file:///").href);
            setConfig(mod.config || mod.default);
            console.log("  [denote] Config reloaded");
            server.hot.send({ type: "full-reload" });
          } catch (e: unknown) {
            const msg = e instanceof Error ? e.message : String(e);
            console.error("  [denote] Config reload error:", msg);
          }
        }
      });
    },
  };
}

export default defineConfig({
  plugins: [
    denoteConfigHmr(),
    fresh({ serverEntry: ".denote/main.ts", clientEntry: ".denote/client.ts", islandSpecifiers }),
    tailwindcss(),
  ],
  server: {
    port: ${port},
    host: true,
  },
});
`,
  );
}

async function devCommand(port: number) {
  const { configPath } = await loadUserConfig();

  console.log(`\n${bold("🦕 Denote")} ${dim(`v${VERSION}`)}`);
  console.log(`${dim("  Config:")} ${configPath}`);
  console.log(`${dim("  Server:")} ${cyan(`http://localhost:${port}`)}\n`);

  await generateBuildFiles(configPath, port);

  // Run vite dev from .denote/ — config hot-reload is handled by the generated Vite plugin
  const command = new Deno.Command(Deno.execPath(), {
    args: ["run", "-A", "npm:vite", "--config", ".denote/vite.config.ts"],
    cwd: Deno.cwd(),
    stdout: "inherit",
    stderr: "inherit",
  });

  const child = command.spawn();
  await child.status;
}

async function buildCommand() {
  const { configPath } = await loadUserConfig();

  console.log(`\n${bold("🦕 Denote Build")} ${dim(`v${VERSION}`)}`);
  console.log(`${dim("  Config:")} ${configPath}\n`);

  await generateBuildFiles(configPath);

  // Run vite build from .denote/
  const command = new Deno.Command(Deno.execPath(), {
    args: [
      "run",
      "-A",
      "npm:vite",
      "build",
      "--config",
      ".denote/vite.config.ts",
    ],
    cwd: Deno.cwd(),
    stdout: "inherit",
    stderr: "inherit",
  });

  const { code } = await command.output();
  if (code !== 0) {
    console.error(red("\nBuild failed."));
    Deno.exit(code);
  }

  console.log(green("\n✓ Build complete!"));
  console.log(dim("  Output: _fresh/\n"));
}

// ── Main ──────────────────────────────────────────────────────

if (import.meta.main) {
  const args = Deno.args;
  const command = args[0];

  if (!command || args.includes("-h") || args.includes("--help")) {
    printHelp();
    Deno.exit(0);
  }

  if (args.includes("-v") || args.includes("--version")) {
    console.log(`denote ${VERSION}`);
    Deno.exit(0);
  }

  // Parse --port
  const portIdx = args.indexOf("--port") !== -1
    ? args.indexOf("--port")
    : args.indexOf("-p");
  const port = portIdx !== -1 ? parseInt(args[portIdx + 1]) || 8000 : 8000;

  switch (command) {
    case "dev":
      await devCommand(port);
      break;

    case "build":
      await buildCommand();
      break;

    case "validate": {
      const { config } = await loadUserConfig();
      const { resolve } = await import("@std/path");
      const { validateAndPrint } = await import("./lib/validate.ts");
      const denoteContext = {
        config: config as import("./denote.config.ts").DenoteConfig,
        contentDir: resolve("./content/docs"),
        docsBasePath: "/docs",
      };
      const errorCount = await validateAndPrint(denoteContext);
      Deno.exit(errorCount > 0 ? 1 : 0);
      break;
    }

    case "mcp": {
      // Delegate to the existing mcp.ts with remaining args
      const mcpArgs = args.slice(1);
      // Dynamically import and the mcp.ts handles its own execution
      const mcpPath = new URL("./mcp.ts", import.meta.url).href;
      // Set Deno.args-like behavior by re-running
      const cmd = new Deno.Command(Deno.execPath(), {
        args: ["run", "-A", mcpPath, ...mcpArgs],
        stdout: "inherit",
        stderr: "inherit",
        stdin: "inherit",
      });
      const { code } = await cmd.output();
      Deno.exit(code);
      break;
    }

    default:
      console.error(red(`Unknown command: ${command}`));
      console.error(`Run ${cyan("denote --help")} for usage.`);
      Deno.exit(1);
  }
}
